/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as RcaRouteImport } from './routes/rca'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const RcaRoute = RcaRouteImport.update({
  id: '/rca',
  path: '/rca',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/graph': typeof GraphRoute
  '/lessons': typeof LessonsRoute
  '/rca': typeof RcaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/graph': typeof GraphRoute
  '/lessons': typeof LessonsRoute
  '/rca': typeof RcaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/graph': typeof GraphRoute
  '/lessons': typeof LessonsRoute
  '/rca': typeof RcaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/compliance' | '/graph' | '/lessons' | '/rca' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compliance' | '/graph' | '/lessons' | '/rca' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/graph'
    | '/lessons'
    | '/rca'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  GraphRoute: typeof GraphRoute
  LessonsRoute: typeof LessonsRoute
  RcaRoute: typeof RcaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rca': {
      id: '/rca'
      path: '/rca'
      fullPath: '/rca'
      preLoaderRoute: typeof RcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  GraphRoute: GraphRoute,
  LessonsRoute: LessonsRoute,
  RcaRoute: RcaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
